name: Bug Report
description: 버그를 보고합니다
labels: ["bug"]
body:
  - type: textarea
    id: symptom
    attributes:
      label: 증상
      description: 어떤 문제가 발생하는가? 재현 조건을 포함해 주세요.
    validations:
      required: true
  - type: textarea
    id: cause
    attributes:
      label: 원인 (파악된 경우)
      description: 기술적 원인을 설명해 주세요.
  - type: textarea
    id: solution
    attributes:
      label: 해결 방안
      description: 계획된 수정 방법을 설명해 주세요.
  - type: dropdown
    id: priority
    attributes:
      label: 우선순위
      options:
        - 긴급 (서비스 장애)
        - 높음 (기능 장애)
        - 보통 (불편)
        - 낮음 (개선)
    validations:
      required: true
