name: Feature Request
description: 신규 기능을 요청합니다
labels: ["feat"]
body:
  - type: textarea
    id: goal
    attributes:
      label: 목표
      description: 무엇을 만들 것인가?
      placeholder: "예: 실시간 가격 데이터 수집 모듈"
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: 요구사항
      description: 기능 명세 및 UI/UX 요구사항
      placeholder: |
        - MutationObserver를 사용한 실시간 가격 업데이트
        - 초당 1회 이상의 업데이트 처리
    validations:
      required: true
  - type: textarea
    id: tech
    attributes:
      label: 기술 스택
      description: 사용할 라이브러리/프레임워크
      placeholder: "React, TypeScript, Dexie.js 등"
  - type: textarea
    id: done
    attributes:
      label: 완료 조건 (Definition of Done)
      description: 체크리스트 형태로 작성해 주세요
      placeholder: |
        - [ ] 유닛 테스트 작성 및 통과
        - [ ] 코드 리뷰 완료
        - [ ] 수동 테스트 완료
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: 우선순위
      description: 작업의 중요도를 선택하세요
      options:
        - p0 (긴급)
        - p1 (높음)
        - p2 (보통)
      default: 2
    validations:
      required: false
  - type: dropdown
    id: effort
    attributes:
      label: 예상 작업량
      description: 대략적인 작업 규모
      options:
        - XS (1-2시간)
        - S (반나절)
        - M (1-2일)
        - L (3-5일)
        - XL (1주 이상)
      default: 2
    validations:
      required: false
