name: Refactoring
description: 리팩토링 작업을 요청합니다
labels: ["refactor"]
body:
  - type: textarea
    id: problem
    attributes:
      label: 현재 문제
      description: 왜 리팩토링이 필요한가?
    validations:
      required: true
  - type: textarea
    id: improvement
    attributes:
      label: 개선 목표
      description: 어떻게 개선할 것인가?
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: 영향 범위
      description: 변경될 모듈/파일
  - type: textarea
    id: rollback
    attributes:
      label: 롤백 계획
      description: 문제 발생 시 대응 방안
